model: gemini-3.8-flash
api: google
concurrent_requests: 64
max_tokens: 65536
cache_read_cost: 0.075
read_cost: 0.75
tool_choice: auto
write_cost: 3.75
human_readable_id: Gemini 3.8 Flash (low)
date: "2026-09-02"
reasoning_effort: low
other_params:
  open: false
  creator: Google
