model: muse-spark-1.3
api: meta
harness: muse
harness_version: "1.0.3-R2198.1"
harness_config:
  max_recovery_attempts: 3
concurrent_requests: 12
use_openai_responses_api: true
use_openai_responses_api_tools: false
stream_openai_responses: true
reasoning_effort: max
max_tokens: 1000000
store: false
include:
  - reasoning.encrypted_content
read_cost: 1.25
cache_read_cost: 0.15
write_cost: 4.25
human_readable_id: Muse Spark 1.3
date: "2026-09-02"
other_params:
  open: false
  creator: Meta AI
