"""Public facade for the harness-wrapper package."""

from .agent import Agent, AgentEvent
from .installation import (
    DEFAULT_CLI_CACHE,
    DEFAULT_CLI_HOME,
    DEFAULT_CLI_VERSION,
    SUPPORTED_CLI_RELEASES,
    CLIRelease,
    InstalledCLI,
    cli_bin_dir,
    cli_environment,
    ensure_cli,
    install_clis,
    installed_versions,
    resolve_cli_release,
)
from .model import Model, create_model
from .models import (
    AbstractModel,
    AnthropicOAuthModel,
    APIEndpoint,
    APIModel,
    APIType,
    AuthenticationError,
    CredentialStore,
    KimiOAuthModel,
    OAuthConfig,
    OAuthCredential,
    OAuthModel,
    OpenAIOAuthModel,
    RateLimit,
    RateLimitPollingUnsupported,
    RateLimitSnapshot,
    RateLimitTimeout,
)
from .sandbox import (
    CommandResult,
    HostServiceRoute,
    LocalSandbox,
    PodmanSandbox,
    Sandbox,
    SandboxMount,
)
from .tools import (
    CLIProcessError,
    ExecutableNotFoundError,
    HarnessError,
    ModelCompatibilityError,
    SessionCache,
    UnsupportedCLIVersionError,
)
from .traces import TokenUsage, Trace, TraceEvent
from .visualization import render_trace_html

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_CLI_CACHE",
    "DEFAULT_CLI_HOME",
    "DEFAULT_CLI_VERSION",
    "SUPPORTED_CLI_RELEASES",
    "APIEndpoint",
    "APIModel",
    "APIType",
    "AbstractModel",
    "Agent",
    "AgentEvent",
    "AnthropicOAuthModel",
    "AuthenticationError",
    "CLIProcessError",
    "CLIRelease",
    "CommandResult",
    "CredentialStore",
    "ExecutableNotFoundError",
    "HarnessError",
    "HostServiceRoute",
    "InstalledCLI",
    "KimiOAuthModel",
    "LocalSandbox",
    "Model",
    "ModelCompatibilityError",
    "OAuthConfig",
    "OAuthCredential",
    "OAuthModel",
    "OpenAIOAuthModel",
    "PodmanSandbox",
    "RateLimit",
    "RateLimitPollingUnsupported",
    "RateLimitSnapshot",
    "RateLimitTimeout",
    "Sandbox",
    "SandboxMount",
    "SessionCache",
    "TokenUsage",
    "Trace",
    "TraceEvent",
    "UnsupportedCLIVersionError",
    "cli_bin_dir",
    "cli_environment",
    "create_model",
    "ensure_cli",
    "install_clis",
    "installed_versions",
    "render_trace_html",
    "resolve_cli_release",
]
