instruction: |
  You are given a difficult question. Your task is to solve the problem.
  Put the final answer you find within \\boxed{{}}.
strict_parsing: false
n_problems: 40
date: "2026-04-01"
dataset_path: MathArena/arxivmath-0426
